---
layers: []
package:
  meta: ~
  depends: ~
  sources: ~
  stages:
    fetch:
      prescript:
        - "mkdir -pv /hostdir/distfiles"
      script: |
        cd /hostdir/distfiles
        for src in "${X10_SOURCES_URLS[@]}"; do
          test -e $(basename "$src") || curl -LO "$src"
        done
    _gensum:
      script: |
        cd /hostdir/distfiles
        for src in "${X10_SOURCES_URLS[@]}"; do
          sha256sum $(basename "$src")
        done
    verify:
      script: |
        cd /hostdir/distfiles
        for i in "${!X10_SOURCES_URLS[@]}"; do
          echo "${X10_SOURCES_CHECKSUMS[$i]}  $(basename "${X10_SOURCES_URLS[$i]}")" | sha256sum -c -
        done
    extract:
      prescript:
        - "rm -rf /builddir/$(basename $X10_META_UNPACK_DIR)-$X10_META_VERSION"
      script: |
        cd /builddir
        for src in "${X10_SOURCES_URLS[@]}"; do
          src=/hostdir/distfiles/$(basename "$src")
          test -d $(basename $X10_META_UNPACK_DIR)-$X10_META_VERSION || {
            tar xf "$src" --no-same-owner
          }
        done
    configure:
      prescript:
        - "ldconfig"
      useworkdir: true
    build:
      useworkdir: true
    test:
      useworkdir: true
    install:
      prescript:
        - 'rm -rf /destdir/"$X10_PACKAGE_FQN"'
      useworkdir: true
    package:
      prescript:
        - 'mkdir -pv $(dirname /hostdir/binpkgs/"$X10_PACKAGE_FQN")'
        - |
          for hook in $(ls /etc/x10/hooks.d); do
            test -x /etc/x10/hooks.d/$hook && /etc/x10/hooks.d/$hook
          done
      script: |
        tar cfJ /hostdir/binpkgs/"$X10_PACKAGE_FQN".tar.xz -C "$DESTDIR" .
  stageorder:
    - fetch
    - verify
    - extract
    - patch
    - configure
    - build
    - test
    - install
    - package
  environment: ~
  workdir: "/builddir/$(basename $X10_META_UNPACK_DIR)-$X10_META_VERSION"
