---
layers: ["makefile"]
package:
  stages:
    configure:
      script: |
        test -n "$USE_BUILDDIR" && {
          mkdir -pv build
          cd build
          CONFIGURE=../configure
        }
        ${CONFIGURE:-./configure} --prefix=/usr --libdir=/usr/lib $CONFIGURE_ARGS
