version: "5.19.5"
bdepend:
  - util/cmake
  - util/extra-cmake-modules
  - virtual/kde-frameworks
  - gui/gtk2
  - gui/gtk3
  - gui/gsettings-desktop-schemas
rdepend:
  - virtual/kde-frameworks
  - gui/gtk2
  - gui/gtk3
  - gui/gsettings-desktop-schemas
filename: kde-gtk-config
upstream: https://download.kde.org/stable/plasma/%{version}
use_build_dir: true
configure: cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -Wno-dev ../%{unpack_dir}
